apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhino
spec:
  template:
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command: ["/cloud_sql_proxy",
                    "-instances=plos-dev:us-east1:ambradb-plos-dev-db1=tcp:3306"]
          securityContext:
            runAsUser: 2
            allowPrivilegeEscalation: false
