#!/usr/bin/env bash
#set -x
set -o errexit

. /usr/share/debconf/confmodule

NAME=rhino

TOMCAT8_USER=$NAME
TOMCAT8_GROUP=$NAME
HOME=/opt/plos/$NAME

function process_env_template {
	CONTEXT_TEMPLATE=$1
	OUTFILE=$2

  ls -lh $CONTEXT_TEMPLATE

	echo "Processing template $CONTEXT_TEMPLATE"

  eval "cat <<EOF
$(<$CONTEXT_TEMPLATE)
EOF
" > $OUTFILE
}

case "$1" in
  configure|reconfigure)

  # create user/group

	if ! getent group "$TOMCAT8_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$TOMCAT8_GROUP" --quiet
	fi
	if ! id $TOMCAT8_USER > /dev/null 2>&1 ; then
	    adduser --system --home $HOME --no-create-home \
		--ingroup "$TOMCAT8_GROUP" --disabled-password --shell /bin/false \
		"$TOMCAT8_USER"
	fi

	chmod +x $HOME/bin/*.sh
	chown -Rh $TOMCAT8_USER:$TOMCAT8_GROUP $HOME

	echo "Fetching configuration from debconf"
	GET="db_get [[artifactId]]"

########### BEGIN app-specific code ###########

  # Fetching configuration from debconf

  $GET/rhino_db_name && export RHINO_DB_NAME=$RET
  $GET/rhino_db_host && export RHINO_DB_HOST=$RET
  $GET/rhino_db_user && export RHINO_DB_USER=$RET
  $GET/rhino_db_password && export RHINO_DB_PASSWORD=$RET
  $GET/rhino_port && export RHINO_PORT=$RET
  $GET/control_port && export CONTROL_PORT=$RET
  $GET/tomcat_admin_user && export TOMCAT_ADMIN_USER=$RET
  $GET/tomcat_admin_password && export TOMCAT_ADMIN_PASSWORD=$RET

########### END app-specific code ###########

	process_env_template $HOME/conf/context.template.xml $HOME/conf/context.xml

	process_env_template $HOME/conf/server.template.xml $HOME/conf/server.xml

  process_env_template $HOME/conf/tomcat-users.template.xml $HOME/conf/tomcat-users.xml

	process_env_template $HOME/bin/setenv.template.sh $HOME/bin/setenv.sh

	invoke-rc.d [[artifactId]] restart

  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac
