#!/usr/bin/env bash

#set -x
set -o errexit

. /usr/share/debconf/confmodule

TOMCAT7_USER=[[artifactId]]
TOMCAT7_GROUP=[[artifactId]]
HOME=[[rhino.debInstallDir]]

function process_env_template {
	CONTEXT_TEMPALTE=$1

  ls -lh $CONTEXT_TEMPALTE

	echo "Processing template $CONTEXT_TEMPALTE"

  eval "cat <<EOF
$(<$CONTEXT_TEMPALTE)
EOF
" > $CONTEXT_TEMPALTE
}

case "$1" in
    configure)

  # create user/group

	if ! getent group "$TOMCAT7_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$TOMCAT7_GROUP" --quiet
	fi
	if ! id $TOMCAT7_USER > /dev/null 2>&1 ; then
	    adduser --system --home $HOME --no-create-home \
		--ingroup "$TOMCAT7_GROUP" --disabled-password --shell /bin/false \
		"$TOMCAT7_USER"
	fi

  chmod +x $HOME/bin/*.sh
  chown -Rh $TOMCAT7_USER:$TOMCAT7_GROUP $HOME

  GET="db_get [[artifactId]]"

  # Fetching configuration from debconf

  $GET/ned_db_host && export NED_DB_HOST=$RET
  $GET/ned_db_user && export NED_DB_USER=$RET
  $GET/ned_db_password && export NED_DB_PASSWORD=$RET
  $GET/ringgold_db_host && export RINGGOLD_DB_HOST=$RET
  $GET/ringgold_db_user && export RINGGOLD_DB_USER=$RET
  $GET/ringgold_db_password && export RINGGOLD_DB_PASSWORD=$RET
  $GET/ringgold_import_dir && export RINGGOLD_DIR=$RET
  $GET/http_port && export HTTP_PORT=$RET
  $GET/control_port && export CONTROL_PORT=$RET

  # removes the saved values, so they need to be re-entered the next time around
  db_purge

  # generate configs from templates
  process_env_template $HOME/conf/context.xml
  cat $HOME/conf/context.xml

  process_env_template $HOME/conf/server.xml
  cat $HOME/conf/server.xml

esac


# Automatically added by dh_installinit
#if [ -x "/etc/init.d/[[artifactId]]" ] || [ -e "/etc/init/[[artifactId]].conf" ]; then
#	if [ ! -e "/etc/init/[[artifactId]].conf" ]; then
#		update-rc.d ned defaults 92 08 >/dev/null
#	fi
#	invoke-rc.d [[artifactId]] start || true
#fi
# End automatically added section
