#!/usr/bin/env bash

#set -x
#set -o errexit

. /usr/share/debconf/confmodule

INPUT="db_input high [[artifactId]]"

$INPUT/ned_db_host || true
$INPUT/ned_db_user || true
$INPUT/ned_db_password || true
$INPUT/ringgold_db_host || true
$INPUT/ringgold_db_user || true
$INPUT/ringgold_db_password || true
$INPUT/ringgold_import_dir || true
$INPUT/http_port || true
$INPUT/control_port || true

db_go || true
